---

- block:
    - name: Check variables
      ansible.builtin.assert:
        that:
          - deconz_platform in deconz_platforms
          - deconz_role_action in deconz_role_actions
  tags: always

...
