---

- name: restart deconz
  ansible.builtin.service:
    name: deconz
    state: restarted
  become: '{{ do_become }}'

- name: reload systemd
  ansible.builtin.systemd:
    daemon-reload: true
  become: '{{ do_become }}'

...
